name: Build on Tag

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

jobs:
  lint:
    name: Lint files
    runs-on:
      group: nscale-k8s
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b
        with:
          go-version: '1.24.1'
      - name: golangci-lint
        uses: golangci/golangci-lint-action@4696ba8babb6127d732c3c6dde519db15edab9ea
        with:
          version: latest
          skip-cache: true
          args: --timeout=30m

  test:
    name: Run tests
    runs-on:
      group: nscale-k8s
    needs: lint
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b
        with:
          go-version: '1.24.1'
      - run: go test -v -cover ./...

  security-checks:
    runs-on:
      group: nscale-k8s
    needs: test
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Build Baski Image
        uses: drewbernetes/container-security-action@0cfb20f5ee342ef3ce3f46f288ed09927d2c28fa
        if: github.event_name != 'pull_request'
        id: build-and-scan-baski
        with:
          image-repo: "drewviles"
          repo-username: ${{ secrets.DOCKER_USER }}
          repo-password: ${{ secrets.DOCKER_PASSWORD }}
          image-name: baski
          image-tag: ${{ github.ref_name }}
          check-severity: "HIGH,CRITICAL"
          grypeignore-from-s3: true
          s3-endpoint: "https://api.s3.hudson-viles.uk/"
          s3-access-key: ${{secrets.S3_ACCESS_KEY}}
          s3-secret-key: ${{secrets.S3_SECRET_KEY}}
          s3-bucket: "grypeignores"
          s3-path: "baski"
          add-latest-tag: true
          publish-image: true
          cosign-private-key: ${{secrets.COSIGN_KEY}}
          cosign-password: ${{secrets.COSIGN_PASSWORD}}
          cosign-tlog: false
          dockerfile-path: docker
